#!/bin/bash
set -e

ACETONEROOT="$(dirname $(realpath $0))"

DEVICES="generic_x86"

if [[ -z "$DEVICE" ]]; then
	echo "No device supplied in \$DEVICE env var, pick one of: $DEVICES"
	exit 1
fi

if echo "$DEVICES" | grep -qv "$DEVICE"; then
	echo "Invalid device detected, expected one of: $DEVICES, got: $DEVICE"
	exit 1
fi

source "$ACETONEROOT/devinfo"

"$ACETONEROOT/mk-peroxide-initrd"
"$ACETONEROOT/mk-kernel"

mkdir -p "$ACETONEROOT/out/"
cp "$ACETONEROOT/tmp/kernel/repo/arch/x86_64/boot/bzImage" "$ACETONEROOT/out/$DEVICE-acetone.efi"

echo "Built Acetone-EFI image for $DEVICE to ./out/$DEVICE-acetone.efi"
