#!/bin/bash
set -e

# make sure we got the repo
if [[ -e "$TMP/kernel" ]]; then
	git -C "$TMP/kernel" pull
else
	git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git -b "linux-6.0.y" "$TMP/kernel"
fi


cd "$TMP/kernel"

cp "$TMP/peroxide/peroxide-$RUSTARCH.cpio" "./initrd.cpio"
cp "$ACETONEROOT/data/$DEVICE-defconfig" ./.config
make olddefconfig
#make nconfig
make -j$(nproc)
