#!/bin/bash
set -e

ACETONEROOT="$(dirname $(realpath $0))"

DEVICES="odroidgo2"

if [[ -z "$DEVICE" ]]; then
	echo "No device supplied in \$DEVICE env var, pick one of: $DEVICES"
	exit 1
fi

if echo "$DEVICES" | grep -qv "$DEVICE"; then
	echo "Invalid device detected, expected one of: $DEVICES, got: $DEVICE"
	exit 1
fi

source "$ACETONEROOT/devinfo"

"$ACETONEROOT/mk-peroxide-initrd" "$RUSTARCH"
"$ACETONEROOT/mk-kernel" "$DEVICE"
"$ACETONEROOT/mk-u-boot" "$DEVICE"
